[package]
name = "seru"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
logos = "0.16.1"
skia-safe = { version = "0.97.2", features = ["svg", "textlayout"] }
taffy = "0.10.1"
ureq = { version = "3" }

[lib]
name = "seru"
path = "src/lib.rs"

[features]
webp = ["skia-safe/webp"]
